// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'src/thing.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 3534494805469766675),
      name: 'Thing',
      lastPropertyId: const obx_int.IdUid(10, 1472944842726310423),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8491193594695295887),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8915662527189686512),
            name: 'content',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8845361712191555473),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4489438415895978020),
            name: 'done',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 2486335390945327863),
            name: 'tags',
            type: 30,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 7667379632905956439),
            name: 'value',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 1472944842726310423),
            name: 'rank',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(3, 5431818547799211746),
            name: 'children',
            targetId: const obx_int.IdUid(5, 3534494805469766675))
      ],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'parents', srcEntity: 'Thing', srcField: 'children')
      ])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) {
  return obx.Store(getObjectBoxModel(),
      directory: directory,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(5, 3534494805469766675),
      lastIndexId: const obx_int.IdUid(2, 5876970679639637568),
      lastRelationId: const obx_int.IdUid(3, 5431818547799211746),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [
        1631627817501562807,
        5074736434067970976,
        3624636574726604689,
        7002050964441799220
      ],
      retiredIndexUids: const [5876970679639637568],
      retiredPropertyUids: const [
        2840272927915169489,
        958694595439191411,
        4544843419996755169,
        2568087456281045795,
        2964913559125229487,
        2451480565332523315,
        6682837070591412613,
        9035978168206840996,
        2750005277514529752,
        2546292154991111937,
        4261564895852394679,
        2739063483213758185,
        5705228549106420783,
        5163927671201236105,
        3696488773815310160,
        4307723726814652867,
        421814647252034290,
        8344290899505051100
      ],
      retiredRelationUids: const [7142782651244064316],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Thing: obx_int.EntityDefinition<Thing>(
        model: _entities[0],
        toOneRelations: (Thing object) => [],
        toManyRelations: (Thing object) => {
              obx_int.RelInfo<Thing>.toMany(3, object.id): object.children,
              obx_int.RelInfo<Thing>.toManyBacklink(3, object.id):
                  object.parents
            },
        getId: (Thing object) => object.id,
        setId: (Thing object, int id) {
          object.id = id;
        },
        objectToFB: (Thing object, fb.Builder fbb) {
          final contentOffset = fbb.writeString(object.content);
          final tagsOffset = fbb.writeList(
              object.tags.map(fbb.writeString).toList(growable: false));
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, contentOffset);
          fbb.addInt64(2, object.createdAt.millisecondsSinceEpoch);
          fbb.addBool(3, object.done);
          fbb.addOffset(7, tagsOffset);
          fbb.addFloat64(8, object.value);
          fbb.addInt64(9, object.rank);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final contentParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          final doneParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false);
          final valueParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 20);
          final tagsParam = const fb.ListReader<String>(
                  fb.StringReader(asciiOptimization: true),
                  lazy: false)
              .vTableGet(buffer, rootOffset, 18, []);
          final object = Thing(
              content: contentParam,
              createdAt: createdAtParam,
              done: doneParam,
              value: valueParam,
              tags: tagsParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..rank =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          obx_int.InternalToManyAccess.setRelInfo<Thing>(object.children, store,
              obx_int.RelInfo<Thing>.toMany(3, object.id));
          obx_int.InternalToManyAccess.setRelInfo<Thing>(object.parents, store,
              obx_int.RelInfo<Thing>.toManyBacklink(3, object.id));
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Thing] entity fields to define ObjectBox queries.
class Thing_ {
  /// See [Thing.id].
  static final id = obx.QueryIntegerProperty<Thing>(_entities[0].properties[0]);

  /// See [Thing.content].
  static final content =
      obx.QueryStringProperty<Thing>(_entities[0].properties[1]);

  /// See [Thing.createdAt].
  static final createdAt =
      obx.QueryDateProperty<Thing>(_entities[0].properties[2]);

  /// See [Thing.done].
  static final done =
      obx.QueryBooleanProperty<Thing>(_entities[0].properties[3]);

  /// See [Thing.tags].
  static final tags =
      obx.QueryStringVectorProperty<Thing>(_entities[0].properties[4]);

  /// See [Thing.value].
  static final value =
      obx.QueryDoubleProperty<Thing>(_entities[0].properties[5]);

  /// See [Thing.rank].
  static final rank =
      obx.QueryIntegerProperty<Thing>(_entities[0].properties[6]);

  /// see [Thing.children]
  static final children =
      obx.QueryRelationToMany<Thing, Thing>(_entities[0].relations[0]);
}
